### PR TITLE
feat: unify meta tags

### PR DESCRIPTION
**Pull request by jembach**

### CODE REVIEW

**Comment by luflow** [comment]
Will be merged in internal repo

**Comment by kllmanu** [comment]
@luflow could you invite me please to that internal repo?

**Comment by luflow** [comment]
@kllmanu the internal repo will be synced next two weeks (including a lot of enhancements from different pull request) to this public one by @AlexanderBabel and the internal one will be archived so you are already at the right place for the upcoming action 🎉 🚀 

Happy weekend!

**Comment by kllmanu** [comment]
@luflow Thanks, I just wanted to do [a few PRs about the things I've noticed](https://github.com/kllmanu/storefront-starter-kit/commit/7dcaaf2fbcfd24c31ea22f6b5446d6107cc03407) this week during the onboarding to Makaira. 

Happy weekend!

**Pull request closed without merging**
